spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/puntuaciones
        username: root
        password: 
        driver-class-name: org.mariadb.jdbc.Driver

logging.level.org.springframework.jdbc.core: TRACE